#!/usr/bin/env python

import sys
import os

from spackager.spa import compile, _readfile


def main(args):
    args = [unicode(arg, 'utf-8') for arg in args]
    legacy_mode = not ('-l' in args or '--no-legacy' in args) # TODO: optparse
    filename = args[1] if legacy_mode else args[2]

    # XXX: hacky?
    if os.sep in filename:
        cwd = os.path.dirname(filename)
        os.chdir(cwd)
        filename = os.path.basename(filename)

    original = _readfile(filename)
    html = compile(original, legacy_mode)
    outfile = filename.replace('.html', '.spa.html') # TODO: configurable (e.g. stdout)
    f = open(outfile, 'w')
    f.write(html.encode('utf-8'))
    f.close()

    return True


if __name__ == '__main__':
    status = not main(sys.argv)
    sys.exit(status)
